### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud-incubator/spring-cloud-kubernetes#26]

**Comment by jrrickard** [comment]
@spencergibb I enjoy writing tests. Are PRs with additional tests welcome?

**Comment by spencergibb** [comment]
absolutely!

**Comment by jrrickard** [comment]
@spencergibb sorry for the delay, we had a baby. Working on this now, would you prefer multiple PRs (as well as issues) for tests across different modules (i.e. for tests for spring-cloud-kubernetes-discovery, tests for spring-cloud-kubernetes-config), or just in one big PR?

**Comment by spencergibb** [comment]
NP. Congratulations!

I think it's easier to review smaller PRs, so I'd lean that way. @iocanel, thoughts?

**Comment by iocanel** [comment]
Congratulations @jrrickard!

@spencergibb: I also prefer smaller PRs.

**Comment by jrrickard** [comment]
@iocanel @spencergibb couple of follow up questions. Existing tests are mostly written in Groovy, but most other spring-cloud projects seem to have tests written in Java. I started writing in Java but realized I should check if the preference is Java or Groovy for these. 

Related question. If Groovy, should I upgrade the Spock version (1.0 -> 1.1) to support the use of SpringBootTest instead of the deprecated SpringApplicationConfiguration/IntegrationTest? Looks like the 1.1 version of Spock is still RC. 

Thanks!

**Comment by spencergibb** [comment]
Java.

**Comment by bparry02** [comment]
@jrrickard I'd like to contribute some unit tests as well. Which projects are you focusing on initially?

**Comment by cmoulliard** [comment]
As we have started to add Groovy and/or Java Unit Tests, can we close this ticket ?
